import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'
import { Manrope } from 'next/font/google'
import StoryblokBridgeLoader from '@storyblok/react/bridge-loader'
import StoryblokProvider from '../components/StoryblokProvider'

import Page from '@/components/Page'
import Grid from '@/components/Grid'
import Feature from '@/components/Feature'
import Teaser from '@/components/Teaser'

storyblokInit({
  accessToken: 'HAhQiRUwaIYEaJfUHWncWgtt',
  use: [apiPlugin],
  components: {
    feature: Feature,
    grid: Grid,
    page: Page,
    teaser: Teaser
  }
})

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--ff-primary',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png'
  }
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body>{children}</body>
      <StoryblokBridgeLoader options={{}} />
    </html>
  )
}
